const voices=[
['Rachel','Polished Presence','female','en-US'],['Whitney','Composed Concierge','female','en-US'],['Morgan','Executive Expert','female','en-US'],['Cindy','Receptionist','female','en-US'],['Stephanie','Steady Professional','female','en-US'],['Jessica','Clear Communicator','female','en-US'],['Emma','Customer Care Line','female','en-US'],['Valerie','Support Authority','female','en-US'],['Camille','Friendly Expert','female','en-US'],['Doreen','Decisive Coordinator','female','en-US'],
['Reed','Polished Professional','male','en-US'],['Wyatt','Dependable Dispatcher','male','en-US'],['Daniel','Modern Assistant','male','en-US'],['Austin','Conversational Guide','male','en-US'],['Grant','Friendly Support','male','en-US'],['Cole','Clear Communicator','male','en-US'],['Blake','Helpful Agent','male','en-US'],['Levi','Steady Spokesman','male','en-US'],['Derek','Deep Advisor','male','en-US'],['Brent','Steady Conversationalist','male','en-US'],
['Imogen','Polished Guide','female','en-GB'],['Arthur','Polished Advisor','male','en-GB'],['Heath','Calm & Composed','male','en-AU'],['Amelia','Instructor','female','en-AU'],['Siobhan','Warm Welcomer','female','en-IE'],['Conor','Decisive Agent','male','en-IE'],['Priya','Trusted Operator','female','en-IN'],['Sameer','Problem Solver','male','en-IN'],['Anele','Bright Presenter','female','en-ZA'],['Pieter','Polished Analyst','male','en-ZA']
];
const accentNames={'en-US':'American','en-GB':'British','en-AU':'Australian','en-IE':'Irish','en-IN':'Indian','en-ZA':'South African'};
let state={mode:'voicemail',voice:'Rachel',businessNumber:'',lineType:'mobile',questions:['What is your name?','What is the best number to reach you?','What are you calling about?']};
const $=id=>document.getElementById(id);
function renderVoices(){const a=$('accent').value,g=$('gender').value;const list=voices.filter(v=>v[3]===a&&(g==='all'||v[2]===g));$('voiceGrid').innerHTML=list.map(v=>`<button class="voice-card gender-${v[2]} ${state.voice===v[0]?'selected':''}" data-voice="${v[0]}" role="radio" aria-checked="${state.voice===v[0]}"><span class="voice-avatar">${v[0][0]}</span><span class="voice-copy"><strong>${v[0]}</strong><small>${v[1]} · ${v[2]==='female'?'Woman':'Man'}</small></span><span class="voice-play">▶</span></button>`).join('')||'<p class="hint">No voices match these filters.</p>';document.querySelectorAll('.voice-card').forEach(b=>b.onclick=()=>{state.voice=b.dataset.voice;document.querySelectorAll('.voice-card').forEach(x=>x.classList.toggle('selected',x===b));updateSelected()})}
function updateSelected(){const v=voices.find(v=>v[0]===state.voice)||voices[0];$('selectedVoiceLabel').textContent=`${v[0]} · ${accentNames[v[3]]}`}
function renderQuestions(){$('questions').innerHTML=state.questions.map((q,i)=>`<div class="question-row"><input aria-label="Question ${i+1}" value="${q.replaceAll('"','&quot;')}"><button aria-label="Remove question ${i+1}">×</button></div>`).join('');[...document.querySelectorAll('.question-row')].forEach((row,i)=>{row.querySelector('input').oninput=e=>state.questions[i]=e.target.value;row.querySelector('button').onclick=()=>{state.questions.splice(i,1);renderQuestions()}})}
document.querySelectorAll('.mode-card').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;document.querySelectorAll('.mode-card').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});$('voicemailPanel').classList.toggle('hidden',state.mode!=='voicemail');$('assistantPanel').classList.toggle('hidden',state.mode!=='assistant');$('lineStatus').querySelector('span:last-child').textContent=state.mode==='voicemail'?'Uses your regular voicemail':state.businessNumber?`${state.businessNumber} · Setup required`:'AI line · Not connected'});
$('accent').onchange=renderVoices;$('gender').onchange=renderVoices;$('addQuestion').onclick=()=>{state.questions.push('');renderQuestions();document.querySelector('.question-row:last-child input').focus()};
$('greeting').oninput=e=>$('charCount').textContent=`${e.target.value.length} / 600`;
$('installGreeting').onclick=()=>{$('installResult').classList.remove('hidden');$('installResult').innerHTML='<strong>Generated greeting ready</strong><span>Preview it, then follow the guided carrier recording steps on your phone. New messages will continue appearing in your regular voicemail inbox.</span>';$('lineStatus').querySelector('span:last-child').textContent='Uses your regular voicemail';showToast('Greeting ready to install')};
$('connectButton').onclick=()=>{const number=$('businessNumber').value.trim();if(!/[0-9]{10,}/.test(number.replace(/\D/g,''))){showToast('Enter the number your customers already call');$('businessNumber').focus();return}state.businessNumber=number;state.lineType=$('lineType').value;const label=state.lineType==='mobile'?'cellphone':state.lineType==='landline'?'office line':'VoIP line';$('connectionResult').classList.remove('hidden');$('connectionResult').innerHTML=`<strong>Ready for carrier connection</strong><span>Answer Craft will assign a private routing number, verify ${number}, and show the exact steps to replace voicemail on this ${label}. Customers keep calling the same number.</span>`;$('lineStatus').querySelector('span:last-child').textContent=`${number} · Setup required`;showToast('Number saved — carrier connection is next')};
let voicePreviewAudio=null;
$('previewVoice').onclick=async()=>{const button=$('previewVoice');if(voicePreviewAudio){voicePreviewAudio.pause();voicePreviewAudio.currentTime=0}button.disabled=true;button.textContent='Loading…';try{voicePreviewAudio=new Audio(`voice-samples/${state.voice.toLowerCase()}.mp3`);voicePreviewAudio.preload='auto';voicePreviewAudio.onended=()=>{button.disabled=false;button.textContent='▶ Preview'};await voicePreviewAudio.play();button.textContent='■ Playing'}catch(error){button.disabled=false;button.textContent='▶ Preview';showToast('Voice preview could not play. Please try again.')}};
$('saveButton').onclick=()=>{const payload={...state,businessNumber:$('businessNumber').value,lineType:$('lineType').value,greeting:$('greeting').value,welcome:$('welcome').value,smsEnabled:$('smsEnabled').checked,smsReply:$('smsReply').value,accent:$('accent').value,gender:$('gender').value};localStorage.setItem('answerCraftDraft',JSON.stringify(payload));showToast('Draft saved on this device')};
function showToast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
const saved=JSON.parse(localStorage.getItem('answerCraftDraft')||'null');if(saved){state={...state,...saved};$('greeting').value=saved.greeting||$('greeting').value;$('welcome').value=saved.welcome||$('welcome').value;$('smsEnabled').checked=saved.smsEnabled??true;$('smsReply').value=saved.smsReply||$('smsReply').value;$('accent').value=saved.accent||'en-US';$('gender').value=saved.gender||'all';document.querySelector(`[data-mode="${state.mode}"]`)?.click()}
$('charCount').textContent=`${$('greeting').value.length} / 600`;renderQuestions();renderVoices();updateSelected();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
